-- Schema for skopos
-- Uses UUIDv7-compatible text identifiers generated by the application.
CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    workspace TEXT NOT NULL,
    status TEXT NOT NULL,
    started_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS agents (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    workspace TEXT NOT NULL,
    first_seen_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_states (
    session_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    agent_type TEXT NOT NULL,
    workspace TEXT NOT NULL,
    status TEXT NOT NULL,
    progress INTEGER,
    step_current INTEGER,
    step_total INTEGER,
    message TEXT NOT NULL DEFAULT '',
    snippet TEXT NOT NULL DEFAULT '',
    metadata TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL,
    original_status TEXT,
    stuck_at TEXT,
    git_branch TEXT,
    PRIMARY KEY (session_id, agent_id),
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS events (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    agent_type TEXT NOT NULL,
    workspace TEXT NOT NULL,
    status TEXT NOT NULL,
    progress INTEGER,
    step_current INTEGER,
    step_total INTEGER,
    message TEXT NOT NULL DEFAULT '',
    snippet TEXT NOT NULL DEFAULT '',
    metadata TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sessions_updated_at ON sessions(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_states_session_id ON agent_states(session_id);
CREATE INDEX IF NOT EXISTS idx_agent_states_health ON agent_states(status, updated_at, stuck_at);
CREATE INDEX IF NOT EXISTS idx_events_session_created_at ON events(session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_agent_created_at ON events(agent_id, created_at DESC);

CREATE TABLE IF NOT EXISTS blackboard_entries (
    id              TEXT PRIMARY KEY,
    workspace_id    TEXT,
    scope           TEXT NOT NULL,
    branch_name     TEXT,
    session_id      TEXT,
    entry_type      TEXT NOT NULL,
    title           TEXT NOT NULL,
    content         TEXT NOT NULL DEFAULT '',
    code_ref        TEXT,
    author_agent_id TEXT NOT NULL,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_blackboard_workspace ON blackboard_entries(workspace_id, scope, branch_name);
CREATE INDEX IF NOT EXISTS idx_blackboard_scope   ON blackboard_entries(scope, branch_name);
CREATE INDEX IF NOT EXISTS idx_blackboard_session ON blackboard_entries(session_id);
CREATE INDEX IF NOT EXISTS idx_blackboard_type    ON blackboard_entries(entry_type);

CREATE TABLE IF NOT EXISTS plans (
    id              TEXT PRIMARY KEY,
    workspace_id    TEXT,
    name            TEXT NOT NULL,
    branch_name     TEXT,
    description     TEXT NOT NULL DEFAULT '',
    status          TEXT NOT NULL DEFAULT 'active',
    author_agent_id TEXT NOT NULL,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS plan_items (
    id                  TEXT PRIMARY KEY,
    plan_id             TEXT NOT NULL,
    title               TEXT NOT NULL,
    description         TEXT NOT NULL DEFAULT '',
    phase               TEXT,
    status              TEXT NOT NULL DEFAULT 'pending',
    position            INTEGER NOT NULL DEFAULT 0,
    claimed_by_agent_id TEXT,
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL,
    FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS plan_item_dependencies (
    item_id           TEXT NOT NULL,
    depends_on_item_id TEXT NOT NULL,
    PRIMARY KEY (item_id, depends_on_item_id),
    FOREIGN KEY (item_id) REFERENCES plan_items(id) ON DELETE CASCADE,
    FOREIGN KEY (depends_on_item_id) REFERENCES plan_items(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS plan_dependencies (
    plan_id             TEXT NOT NULL,
    depends_on_plan_id  TEXT NOT NULL,
    PRIMARY KEY (plan_id, depends_on_plan_id),
    FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE,
    FOREIGN KEY (depends_on_plan_id) REFERENCES plans(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_plans_workspace ON plans(workspace_id, branch_name);
CREATE INDEX IF NOT EXISTS idx_plans_branch    ON plans(branch_name);
CREATE INDEX IF NOT EXISTS idx_plan_items_plan ON plan_items(plan_id, position);
CREATE INDEX IF NOT EXISTS idx_item_deps_item  ON plan_item_dependencies(item_id);
CREATE INDEX IF NOT EXISTS idx_item_deps_dep   ON plan_item_dependencies(depends_on_item_id);
CREATE INDEX IF NOT EXISTS idx_plan_deps_plan  ON plan_dependencies(plan_id);
CREATE INDEX IF NOT EXISTS idx_plan_deps_dep   ON plan_dependencies(depends_on_plan_id);
